github-repo: "https://github.com/spring-io/concourse-release-scripts.git"
github-repo-name: "spring-io/concourse-release-scripts"
docker-hub-organization: "springci"
artifactory-server: "https://repo.spring.io"
branch: "main"
build-name: "concourse-release-scripts"
pipeline-name: "concourse-release-scripts"
concourse-url: "https://ci.spring.io"
task-timeout: 45m
