anchors:
  docker-resource-source: &docker-resource-source
    username: ((docker-hub-username))
    password: ((docker-hub-password))

resource_types:
- name: registry-image
  type: registry-image
  source:
    <<: *docker-resource-source
    repository: concourse/registry-image-resource
    tag: 1.9.0
- name: artifactory-resource
  type: registry-image
  source:
    <<: *docker-resource-source
    repository: springio/artifactory-resource
    tag: 0.0.18
resources:
- name: git-repo
  type: git
  icon: github-circle
  source:
    uri: ((github-repo))
    username: ((github-username))
    password: ((github-ci-release-token))
    branch: ((branch))
- name: ci-images-git-repo
  type: git
  icon: github-circle
  source:
    uri: ((github-repo))
    branch: ((branch))
    paths: ["ci/images/*"]
- name: ci-image
  type: registry-image
  icon: docker
  source:
    <<: *docker-resource-source
    repository: ((docker-hub-organization))/concourse-release-scripts-ci-image
    tag: 0.4.x
- name: concourse-release-scripts-image
  type: docker-image
  icon: docker
  source:
    <<: *docker-resource-source
    repository: springio/concourse-release-scripts
- name: artifactory-repo
  type: artifactory-resource
  icon: package-variant
  source:
    uri: ((artifactory-server))
    username: ((artifactory-username))
    password: ((artifactory-password))
    build_name: ((build-name))
jobs:
- name: build-ci-image
  plan:
  - get: git-repo
  - get: ci-images-git-repo
    trigger: true
  - task: build-ci-image
    privileged: true
    file: git-repo/ci/tasks/build-ci-image.yml
    output_mapping:
      image: ci-image
    vars:
      ci-image-name: ci-image
  - put: ci-image
    params:
      image: ci-image/image.tar
- name: build
  serial: true
  public: true
  plan:
  - get: ci-image
  - get: git-repo
    trigger: true
  - do:
    - task: build-project
      privileged: true
      timeout: ((task-timeout))
      image: ci-image
      file: git-repo/ci/tasks/build-project.yml
      params:
        BRANCH: ((branch))
  - put: artifactory-repo
    params: &artifactory-params
      repo: libs-snapshot-local
      folder: distribution-repository
      build_uri: "https://ci.spring.io/teams/${BUILD_TEAM_NAME}/pipelines/${BUILD_PIPELINE_NAME}/jobs/${BUILD_JOB_NAME}/builds/${BUILD_NAME}"
      build_number: "${BUILD_PIPELINE_NAME}-${BUILD_JOB_NAME}-${BUILD_NAME}"
      disable_checksum_uploads: true
      threads: 8
    get_params:
      threads: 8
  - put: concourse-release-scripts-image
    params:
      build: .
      dockerfile: git-repo/Dockerfile
      tag: built-artifact/version
      build_args:
        root: git-repo
        jar:  built-artifact/concourse-release-scripts.jar
- name: stage-release
  serial: true
  plan:
  - get: ci-image
  - get: git-repo
    trigger: false
  - task: stage
    image: ci-image
    file: git-repo/ci/tasks/stage.yml
    params:
      RELEASE_TYPE: RELEASE
  - put: artifactory-repo
    params:
      <<: *artifactory-params
      repo: libs-staging-local
  - put: git-repo
    params:
      repository: stage-git-repo
- name: promote-release
  serial: true
  plan:
  - get: ci-image
  - get: git-repo
    trigger: false
  - get: artifactory-repo
    trigger: false
    passed: [stage-release]
    params:
      download_artifacts: true
      save_build_info: true
  - do:
    - task: promote
      image: ci-image
      file: git-repo/ci/tasks/promote.yml
      params:
        RELEASE_TYPE: RELEASE
        ARTIFACTORY_SERVER: ((artifactory-server))
        ARTIFACTORY_USERNAME: ((artifactory-username))
        ARTIFACTORY_PASSWORD: ((artifactory-password))
  - put: concourse-release-scripts-image
    params:
      build: .
      dockerfile: git-repo/Dockerfile
      tag: built-artifact/version
      build_args:
        root: git-repo
        jar:  built-artifact/concourse-release-scripts.jar
groups:
- name: "build"
  jobs: ["build"]
- name: "release"
  jobs: ["stage-release", "promote-release"]
- name: "ci-images"
  jobs: ["build-ci-image"]
